### ISSUE TITLE
Improve WebUI 0.8

### ISSUE THREAD

**Issue by zhzLuke96** [lenML/Speech-AI-Forge#131]
## TODOs
- [x] Support switching models in webui
- [x] Support uploading reference audio
- [x] Add more webui documentation and help information
- [x] Add ASR tab
- [x] Add Audio Editor tools tab
