### ISSUE TITLE
API Demo Examples

### ISSUE THREAD

**Issue by zhzLuke96** [lenML/Speech-AI-Forge#194]
应该增加一个 /examples 展示一些如何使用 api 的代码例子

### TODOs
- [x] python speech-forge client
- [x] js speech-forge client
- [x] tts examples
- [ ] stt examples
- [ ] ssml examples
- [ ] voice clone examples
- [ ] script/speaker_builder
